/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CALCULA 0x20000003
#define CALCVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define START_SERVERS 1
extern  int * start_servers_1(int *, CLIENT *);
extern  int * start_servers_1_svc(int *, struct svc_req *);
#define PASS_TOKEN 2
extern  int * pass_token_1(void *, CLIENT *);
extern  int * pass_token_1_svc(void *, struct svc_req *);
#define P 3
extern  int * p_1(void *, CLIENT *);
extern  int * p_1_svc(void *, struct svc_req *);
#define V 4
extern  int * v_1(void *, CLIENT *);
extern  int * v_1_svc(void *, struct svc_req *);
extern int calcula_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define START_SERVERS 1
extern  int * start_servers_1();
extern  int * start_servers_1_svc();
#define PASS_TOKEN 2
extern  int * pass_token_1();
extern  int * pass_token_1_svc();
#define P 3
extern  int * p_1();
extern  int * p_1_svc();
#define V 4
extern  int * v_1();
extern  int * v_1_svc();
extern int calcula_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
